/**
 * Render the per-user config.py that LumenFlash writes to the Pico. Read by
 * python/main.py via `try: import config`. Keep keys and types stable —
 * downstream Python relies on getattr() with defaults.
 */

export interface PicoConfig {
  readonly width: number;
  readonly height: number;
  readonly ledPin?: number;
  readonly enabledIds: readonly string[];
}

export function renderConfigPy(cfg: PicoConfig): string {
  const pin = cfg.ledPin ?? 19;
  const apps = cfg.enabledIds.map((id) => `"${id}"`).join(", ");
  const trailingComma = cfg.enabledIds.length === 1 ? "," : "";
  return [
    `# Generated by LumenFlash on ${new Date().toISOString()}.`,
    `# Edit at your own risk — re-running the wizard overwrites this file.`,
    ``,
    `DISPLAY_WIDTH = ${cfg.width}`,
    `DISPLAY_HEIGHT = ${cfg.height}`,
    `LED_PIN = ${pin}`,
    `APPS_ENABLED = (${apps}${trailingComma})`,
    ``,
  ].join("\n");
}
