/**
 * Deterministic codegen: design + active preset → runnable JS + Python.
 *
 * For purely frame-based animations (each design page = one frame, optional
 * per-page duration), the user shouldn't have to involve an LLM. The
 * generator walks the design, packs each frame into LED order using the
 * active preset's hardware config, and emits two flavours of the same
 * contract:
 *
 *  - **JS** for the simulator's user-app loader (NAME / run exports,
 *    talks to globalThis.lumatrix for sleep + screens).
 *  - **Py** for the Pico — same shape as python/apps/*.py with a
 *    __main__ standalone block.
 *
 * Both bake the LED indexing in at generate time, so the device code is
 * hardware-agnostic: a flat NUM_LEDS-long array of (r,g,b) tuples per
 * frame, blit directly to `np[i]`. No per-frame index math at runtime.
 */

import { activeConfig } from "./config";
import { computeLedIndex } from "./led-index";
import type { Design } from "./types";

/** Frame interval used when a page has no `duration` set. Quick enough that
 *  a 2-page animation reads as a flash, slow enough that 30+ frames don't
 *  blur into nothing. Easy to tune from the page-meta modal later. */
export const DEFAULT_FRAME_MS = 250;

export interface GeneratedApp {
  /** User-facing name, kept as-is (e.g. "Snake Idle"). */
  readonly name: string;
  /** Python module name + JS user-app id. Lowercase identifier, no spaces. */
  readonly appId: string;
  /** Number of frames the animation contains (= count of pages with a
   *  variant for the active preset). */
  readonly frameCount: number;
  /** Display width / height in LEDs, matching the active preset. */
  readonly width: number;
  readonly height: number;
  /** Source of the ES module a simulator user-app loader can consume. */
  readonly js: string;
  /** Source of the .py file the flash wizard / hand-flash can use. */
  readonly py: string;
}

interface Frame {
  /** LED-indexed array of (r,g,b) tuples or null for off. */
  pixels: ([number, number, number] | null)[];
  durationMs: number;
  /** Crossfade in from the previous frame over this many ms, taken from
   *  the start of `durationMs`. 0 = snap (default). */
  fadeInMs: number;
}

export function generateApp(
  design: Design,
  presetId: string,
  rawName: string,
): GeneratedApp {
  const name = rawName.trim() || "Untitled animation";
  const appId = slugifyModuleName(name);

  const config = activeConfig(design, presetId);
  if (config.width === 0 || config.height === 0) {
    throw new Error(
      `No hardware exists for preset "${presetId}"; can't generate an app.`,
    );
  }
  const width = config.width;
  const height = config.height;

  const frames: Frame[] = [];
  for (const page of design.pages) {
    const variant = page.variants[presetId];
    if (!variant) continue;
    const led: ([number, number, number] | null)[] = new Array(
      width * height,
    ).fill(null);
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const hex = variant.pixels[y * width + x];
        if (!hex) continue;
        const idx = computeLedIndex(x, y, config);
        if (idx < 0 || idx >= led.length) continue;
        led[idx] = hexToRgb(hex);
      }
    }
    frames.push({
      pixels: led,
      durationMs: page.duration ?? DEFAULT_FRAME_MS,
      fadeInMs: page.fadeInTime ?? 0,
    });
  }

  if (frames.length === 0) {
    throw new Error(
      `No pages have a variant for the active hardware. Add at least one before generating.`,
    );
  }

  return {
    name,
    appId,
    frameCount: frames.length,
    width,
    height,
    js: emitJs(name, width, height, frames),
    py: emitPy(name, appId, width, height, frames),
  };
}

// =============================================================
// JS emitter — ES module the simulator's user-app loader accepts
// =============================================================

function emitJs(
  name: string,
  width: number,
  height: number,
  frames: Frame[],
): string {
  const numLeds = width * height;
  const framesJs = frames
    .map((f, i) => `  // page ${i + 1}\n  ${arrayLiteralJs(f.pixels)}`)
    .join(",\n");
  const durationsJs = frames.map((f) => f.durationMs).join(", ");
  const fadeInsJs = frames.map((f) => f.fadeInMs).join(", ");

  return `// Generated by LumenDesigner — frame-loop animation.
// Edit freely: the file is a plain ES module the simulator loads as a user app.

export const NAME = ${jsStringLiteral(name)};

const NUM_LEDS = ${numLeds};

/** Overall brightness. The simulator boosts buffer values ~3.2× when
 *  rendering so apps stay below 255 internally; 0.25 puts the rendered
 *  colour close to the as-designed hex. Bump toward 1.0 for brighter
 *  output (clipped colours wash toward white). */
const BRIGHTNESS = 0.25;

/** Substep granularity for crossfades. ~33 fps; small enough that fades
 *  look smooth, large enough that even short fades take a few steps. */
const FADE_STEP_MS = 30;

/** LED-indexed frames. \`null\` means OFF; a triple is (r,g,b) 0-255 at
 *  full brightness — the runtime scales by BRIGHTNESS on every render. */
const FRAMES = [
${framesJs}
];

/** Per-frame hold time in ms. */
const DURATIONS_MS = [${durationsJs}];

/** Per-frame fade-in time in ms, taken from the start of the frame's
 *  duration. 0 = snap. */
const FADE_INS_MS = [${fadeInsJs}];

const OFF = [0, 0, 0];

function dim(channel) {
  return Math.round(channel * BRIGHTNESS);
}

function writeBlended(np, from, to, t) {
  for (let i = 0; i < NUM_LEDS; i++) {
    const a = from[i] ?? OFF;
    const b = to[i] ?? OFF;
    np[i] = [
      dim(a[0] + (b[0] - a[0]) * t),
      dim(a[1] + (b[1] - a[1]) * t),
      dim(a[2] + (b[2] - a[2]) * t),
    ];
  }
  np.write();
}

async function showFrame(np, prev, target, fadeMs, durationMs, check_exit, sleep_ms) {
  const fade = Math.min(fadeMs, durationMs);
  if (fade > 0) {
    const steps = Math.max(1, Math.round(fade / FADE_STEP_MS));
    const stepMs = fade / steps;
    for (let s = 1; s <= steps; s++) {
      if (check_exit()) return true;
      writeBlended(np, prev, target, s / steps);
      await sleep_ms(stepMs);
    }
  } else {
    writeBlended(np, target, target, 1);
  }
  const hold = durationMs - fade;
  if (hold > 0) await sleep_ms(hold);
  return check_exit();
}

export async function run(np, joy, display, screensNp) {
  const runtime = globalThis.lumatrix;
  if (!runtime) throw new Error("LumenLab runtime is not installed");
  const { sleep_ms, screens } = runtime;

  screens.init(screensNp ?? np, joy, display?.width, display?.height);
  if ((await screens.loading_screen()) === "exit") return;

  let prev = new Array(NUM_LEDS).fill(null);
  let i = 0;
  const n = FRAMES.length;
  while (true) {
    if (screens.check_exit()) return;
    const target = FRAMES[i % n];
    const exited = await showFrame(
      np,
      prev,
      target,
      FADE_INS_MS[i % n],
      DURATIONS_MS[i % n],
      screens.check_exit,
      sleep_ms,
    );
    if (exited) return;
    prev = target;
    i++;
  }
}
`;
}

// =============================================================
// Python emitter — file the Pico picks up under /apps/
// =============================================================

function emitPy(
  name: string,
  appId: string,
  width: number,
  height: number,
  frames: Frame[],
): string {
  const numLeds = width * height;
  const framesPy = frames
    .map((f, i) => `    # page ${i + 1}\n    ${tupleListPy(f.pixels)}`)
    .join(",\n");
  const durationsPy = frames.map((f) => f.durationMs).join(", ");
  const fadeInsPy = frames.map((f) => f.fadeInMs).join(", ");

  return `# Generated by LumenDesigner — frame-loop animation.
# Edit freely: this file lives under python/apps/${appId}.py on the device.

from machine import Pin
from neopixel import NeoPixel
from time import sleep_ms
import _screens as screens

NAME = ${pyStringLiteral(name)}

NUM_LEDS = ${numLeds}

# Overall brightness. WS2812 LEDs are very bright; 0.25 keeps the matrix
# comfortable to look at. Bump toward 1.0 for a brighter board.
BRIGHTNESS = 0.25

# Substep granularity for crossfades.
FADE_STEP_MS = 30

# LED-indexed frames. None means OFF; a tuple is (r, g, b) 0-255 at full
# brightness — the runtime scales by BRIGHTNESS on every render.
FRAMES = [
${framesPy},
]

# Per-frame hold time in ms.
DURATIONS_MS = [${durationsPy}]

# Per-frame fade-in time in ms, taken from the start of the frame's
# duration. 0 = snap.
FADE_INS_MS = [${fadeInsPy}]

OFF = (0, 0, 0)

np = None


def write_blended(prev, target, t):
    for i in range(NUM_LEDS):
        a = prev[i] if prev[i] is not None else OFF
        b = target[i] if target[i] is not None else OFF
        np[i] = (
            int((a[0] + (b[0] - a[0]) * t) * BRIGHTNESS),
            int((a[1] + (b[1] - a[1]) * t) * BRIGHTNESS),
            int((a[2] + (b[2] - a[2]) * t) * BRIGHTNESS),
        )
    np.write()


def show_frame(prev, target, fade_ms, duration_ms):
    fade = min(fade_ms, duration_ms)
    if fade > 0:
        steps = max(1, round(fade / FADE_STEP_MS))
        step_ms = fade // steps
        for s in range(1, steps + 1):
            if screens.check_exit():
                return True
            write_blended(prev, target, s / steps)
            sleep_ms(step_ms)
    else:
        write_blended(target, target, 1)
    hold = duration_ms - fade
    if hold > 0:
        sleep_ms(hold)
    return screens.check_exit()


def run(neopixel, joystick, display=None, screens_np=None):
    global np
    np = neopixel
    screens.init(
        screens_np if screens_np is not None else neopixel,
        joystick,
        display["width"] if display else None,
        display["height"] if display else None,
    )
    if screens.loading_screen() == "exit":
        return
    prev = [None] * NUM_LEDS
    i = 0
    n = len(FRAMES)
    while True:
        if screens.check_exit():
            return
        target = FRAMES[i % n]
        if show_frame(prev, target, FADE_INS_MS[i % n], DURATIONS_MS[i % n]):
            return
        prev = target
        i += 1


if __name__ == "__main__":
    _np = NeoPixel(Pin(19, Pin.OUT), NUM_LEDS)
    _joy = {
        "up":     Pin(3, Pin.IN),
        "down":   Pin(6, Pin.IN),
        "left":   Pin(7, Pin.IN),
        "right":  Pin(2, Pin.IN),
        "center": Pin(8, Pin.IN),
        "slide":  Pin(9, Pin.IN),
    }
    run(_np, _joy)
`;
}

// =============================================================
// Formatting helpers
// =============================================================

function arrayLiteralJs(pixels: ([number, number, number] | null)[]): string {
  const parts = pixels.map((p) =>
    p === null ? "null" : `[${p[0]},${p[1]},${p[2]}]`,
  );
  return `[${parts.join(",")}]`;
}

function tupleListPy(pixels: ([number, number, number] | null)[]): string {
  const parts = pixels.map((p) =>
    p === null ? "None" : `(${p[0]},${p[1]},${p[2]})`,
  );
  return `[${parts.join(",")}]`;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.startsWith("#") ? hex.slice(1) : hex;
  if (h.length !== 6) return [0, 0, 0];
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return [
    Number.isFinite(r) ? r : 0,
    Number.isFinite(g) ? g : 0,
    Number.isFinite(b) ? b : 0,
  ];
}

/** Python's `main.py` does `__import__(<id>)` from `/apps/`, so this must
 *  be a valid module identifier: lowercase letters, digits, underscore,
 *  starting with a letter. The slug also doubles as the JS user-app id. */
export function slugifyModuleName(label: string): string {
  const cleaned = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 24);
  // Identifiers can't start with a digit.
  const safe = /^[a-z]/.test(cleaned) ? cleaned : `app_${cleaned}`;
  return safe || "custom_app";
}

function jsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function pyStringLiteral(s: string): string {
  // Python accepts double-quoted strings with backslash escapes — same shape
  // as JSON for our character set (no control chars / no fancy unicode tricks
  // expected in design names).
  return JSON.stringify(s);
}
